---
# tasks file s3-config


- name: Install AW python dependencies
  apt:
    pkg: python-boto
    state: present
  sudo: true


- name: Create a bucket for the host on S3
  # Create a bucket with key as directory, in the Configured region
  s3:
    bucket: "{{ s3cmd_bucket_name }}"
    mode: create
    region: "{{ s3cmd_bucket_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
